### ISSUE TITLE
Supplement for the installation description

### ISSUE THREAD

**Issue by VolkerKa** [hacs/documentation#20]
I have just tried to integrate HACS 0.20.4 and I have unfortunately not succeeded. I followed your instructions exactly, but to no avail. The problem was that the file "custum_updater.py" was in my "custom_components" folder. I deleted the file and everything worked without problems. Can you please insert in your really good description that the "custom_updater.py" file is not available. Thanks again for your effort and great work !!!

**Comment by ludeeus** [comment]
Hi,

This was in the documentation until recently where I removed it, custom_updater has been deprecated for a long time, I will not add that back again.
HA will tell you if you have it installed.

```
This cannot be used with custom_updater.
To use this you need to remove custom_updater form INSTALLATION_LOCATION
```
