### ISSUE TITLE
broken footer links

### ISSUE THREAD

**Issue by ludeeus** [hacs/documentation#23]
probably a z-index issue
![image](https://user-images.githubusercontent.com/15093472/72012833-f52d7b00-325c-11ea-9c37-781a66f8ab90.png)
![image](https://user-images.githubusercontent.com/15093472/72012852-fc548900-325c-11ea-9b9a-7fe2b27aaa7a.png)

**Comment by artmg** [comment]
Lol - your own bot telling you off. Slap it down ;)

I can confirm issue on `what.md` and `upgrade.md` in Chrome and Safari on macos 10.14.6 but **NOT** on `hassio_only.md` 

Try writing another line or two, or put in a heading, then the links might suddenly start working. I would PR but I only started learning about HACS so all my Qs are pretty F. 
@ me if you want a test, though

**Comment by ludeeus** [comment]
It adds that post to all opened issues, no matter how much detail it contains.
