### ISSUE TITLE
I really like HACS and I even create a video tutorial about it

### ISSUE THREAD

**Issue by peyanski** [hacs/documentation#29]
Hi there,

this is my video guide/tutorial - https://youtu.be/4cOdgW23KCA
If you think that the video is helpful you can put it somewhere in the README.md
Or I if it's easier for you I can do that and create a Pull request

Either way keep up the good work.
Cheers,
Kiril

**Comment by ludeeus** [comment]
Maybe it's time to create a section on the documentation site for all the guides/videos created for HACS 
Do you want to start off that section?

**Comment by peyanski** [comment]
Ok, great idea. I will try to create it :)
Thanks @ludeeus
