### ISSUE TITLE
BWALARM is not updating correctly

### ISSUE THREAD

**Issue by Klagio** [hacs/documentation#43]
BWALARM is not updating correctly

https://github.com/akasma74/Hass-Custom-Alarm/issues/90

**Comment by ludeeus** [comment]
okey?
and what does that have to do with the documentation?

**Comment by Klagio** [comment]
Ok, where do the issue go?

**Comment by ludeeus** [comment]
![image](https://user-images.githubusercontent.com/15093472/79568101-8e1e2e80-80b5-11ea-9eeb-d6aeba3bd30c.png)
Read that link
