### ISSUE TITLE
Hassfest doesn't allow minimum homeassistant release in manifest.json

### ISSUE THREAD

**Issue by mudape** [hacs/documentation#44]
Hi,
On https://hacs.xyz/docs/publish/integration#github-releases-optional it says that the minimum homeassistant release can be specified but [hassfest](https://developers.home-assistant.io/blog/2020/04/16/hassfest/) doesn't allow that.

> * [MANIFEST] Invalid manifest: extra keys not allowed @ data['homeassistant']. Got '0.94.0'

**Comment by ludeeus** [comment]
That should be removed, hacs.json is the right place for it
