### ISSUE TITLE
Black and white full screen HACS logo when running in Fully Kiosk

### ISSUE THREAD

**Issue by CharlesMahan** [hacs/documentation#46]
I have fully kiosk installed on Amazon Fire 7 tablet. About half the time when it dismisses the screen saver to show my HA dashboard I instead get a large HACS black and white logo instead. I have to then bypass the liosk mode and reload the page to get the dashboard to install.   Any idea why this would be happening.  I haven't done anything wonky. Just installed it and a couple of custom theme.  
![15878510398662898620463443817240](https://user-images.githubusercontent.com/60854087/80291548-05863a80-8714-11ea-91ed-df540de1131b.jpg)

**Comment by ludeeus** [comment]
You get this one if HA stops showing the frontend, the only remaining thing is the HACS logo.

Try refresh your browser or restart HA.
