### ISSUE TITLE
Question: could you better define "A stable internet connection with sufficient bandwidth"?

### ISSUE THREAD

**Issue by unlucio** [hacs/documentation#49]
I personally judge anything below 50mbit down / 10mbits up connection a bad connection, but due to the current pandemic I'm stuck on a ~12mbit down / it's_not_even_1_mbit up.
How much data (the order of magnitude at least) do you think it will be downloaded during setup and, and what is the timeout?
I guess those would be the 2 factors creating a problem to the installation on a bad connection?

I'm holding off in trying `hacs` right now because I don't think this is a good connection, and because of that line, but without data it's hard to judge.

Thanks

**Comment by ludeeus** [comment]
Speed is not an issue, bandwidth caps are.

**Comment by unlucio** [comment]
Oh you mean data caps!
Ok, no, this thing as slow as it is, can download as much as it's pleased. Drop by drop 😂

**Comment by ludeeus** [comment]
Then you should be fine 👍
